services:
  web:
    image: node:lts
    user: 'node' #you can remove this if you are facing access issues when installing node packages
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
    command: 'npm start'